# Armbook
version: "3"

services:
  webserver:
    container_name: armbook
    build:
      context: ./armbook
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./htdocs/:/var/www/html/
    ports:
      - 80:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: armbook
      MYSQL_USER: armbook
      MYSQL_PASSWORD: secret
    ports:
      - 9906:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - 8080:80
    # Apply armbook.sql via phpmyadmin